### ISSUE TITLE
No sé como imprimir hola mundo

### ISSUE THREAD

**Issue by EmilioSerna** [8ctavio89/Juego-de-Baraja-Francesa-con-clases-#1]
Esto, tengo un gran problema desde aproximadamente hace 4 semestres, en el que me encuentro en una gran dificultad para lograr la "impresión" de un Hola Mundo en cualquier terminal. Estoy en 4to semestre y no sé aún como hacer un Hola Mundo,
de antemano gracias por su lectura y espero ansiosamente su ayuda
El Kks

**Comment by 8ctavio89** [comment]
Es complicado pasar este tipo de conocimiento, más tratándose de un apartado bíblico tan complejo como lo es la ### Santa Escritura del buen código. Le recomiendo seguir los pasos de nuestro señor Linus Sebastian, sentado a la derecha de dios todopoderoso: el **Octavio**. 
Un saludo, espero haber resuelto vuestra duda, mi fiel feligrés.

**Comment by 8ctavio89** [comment]
Se me olvidaba:
`print("Hola, mundo.")`

**Comment by EmilioSerna** [comment]
Oh, dios mío, llevo buscando por mucho tiempo esta respuesta, me sirvió sobretodo cuando empecé a hacer el rezo feligrés, ¡lo logré, muchas gracias todopoderoso **Octavio**!
